package net.nhatjs.js_furniture_mod.core;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.nhatjs.js_furniture_mod.NhatJSFurnitureMod;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TAB =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, NhatJSFurnitureMod.MOD_ID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> JS_FURNITURE_MOD_TABS = CREATIVE_MODE_TAB.register("js_furniture_logo",
            () -> CreativeModeTab.builder().title(Component.translatable("itemgroup.js_furniture_mod.js_furniture_tab"))
                            .icon(() -> new ItemStack(ModBlocks.BLACK_TABLE.get()))
                                    .displayItems((parameters, output) -> {
                                        output.accept(ModBlocks.WOOD_LIGHT_CHAIR);
                                        output.accept(ModBlocks.WOOD_MEDIUM_CHAIR);
                                        output.accept(ModBlocks.BLACK_CHAIR);
                                        output.accept(ModBlocks.WHITE_CHAIR);
                                        output.accept(ModBlocks.BLACK_SOFA);
                                        output.accept(ModBlocks.WHITE_SOFA);
                                        output.accept(ModBlocks.WOOD_LIGHT_TABLE);
                                        output.accept(ModBlocks.WOOD_MEDIUM_TABLE);
                                        output.accept(ModBlocks.BLACK_TABLE);
                                        output.accept(ModBlocks.WHITE_TABLE);
                                        output.accept(ModBlocks.WOOD_LIGHT_COFFEE_TABLE);
                                        output.accept(ModBlocks.WOOD_MEDIUM_COFFEE_TABLE);
                                        output.accept(ModBlocks.BLACK_COFFEE_TABLE);
                                        output.accept(ModBlocks.WHITE_COFFEE_TABLE);
                                        output.accept(ModBlocks.WOOD_LIGHT_DESK);
                                        output.accept(ModBlocks.WOOD_MEDIUM_DESK);
                                        output.accept(ModBlocks.BLACK_DESK);
                                        output.accept(ModBlocks.WHITE_DESK);
                                        output.accept(ModBlocks.WOOD_LIGHT_STANDING_DESK);
                                        output.accept(ModBlocks.WOOD_MEDIUM_STANDING_DESK);
                                        output.accept(ModBlocks.BLACK_STANDING_DESK);
                                        output.accept(ModBlocks.WHITE_STANDING_DESK);
                                        output.accept(ModBlocks.WOOD_LIGHT_STANDING_DESK_B);
                                        output.accept(ModBlocks.WOOD_MEDIUM_STANDING_DESK_B);
                                        output.accept(ModBlocks.BLACK_STANDING_DESK_B);
                                        output.accept(ModBlocks.WHITE_STANDING_DESK_B);
                                        output.accept(ModBlocks.WOOD_LIGHT_3_DRAWER_DRESSER);
                                        output.accept(ModBlocks.WOOD_MEDIUM_3_DRAWER_DRESSER);
                                        output.accept(ModBlocks.BLACK_3_DRAWER_DRESSER);
                                        output.accept(ModBlocks.WHITE_3_DRAWER_DRESSER);
                                        output.accept(ModBlocks.WOOD_LIGHT_TV_STAND);
                                        output.accept(ModBlocks.WOOD_MEDIUM_TV_STAND);
                                        output.accept(ModBlocks.BLACK_TV_STAND);
                                        output.accept(ModBlocks.WHITE_TV_STAND);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_WITH_SINK);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_2);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_2_EXTRA);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B_2);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_DRAWERS);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_DRAWERS_B);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_TOP);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_TOP_B);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_WITH_SINK);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_2);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_2_EXTRA);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B_2);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_DRAWERS);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_DRAWERS_B);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_TOP);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_TOP_B);
                                        output.accept(ModBlocks.BLACK_MIRROR);
                                        output.accept(ModBlocks.BLACK_VERTICAL_BLINDS);
                                        output.accept(ModBlocks.WHITE_VERTICAL_BLINDS);
                                        output.accept(ModBlocks.WOOD_LIGHT_CEILING_FAN_BLACK);
                                        output.accept(ModBlocks.WOOD_MEDIUM_CEILING_FAN_BLACK);
                                        output.accept(ModBlocks.BLACK_CEILING_FAN_BLACK);
                                        output.accept(ModBlocks.WHITE_CEILING_FAN_BLACK);
                                        output.accept(ModBlocks.WOOD_LIGHT_CEILING_FAN_WHITE);
                                        output.accept(ModBlocks.WOOD_MEDIUM_CEILING_FAN_WHITE);
                                        output.accept(ModBlocks.BLACK_CEILING_FAN_WHITE);
                                        output.accept(ModBlocks.WHITE_CEILING_FAN_WHITE);
                                        output.accept(ModBlocks.SOCKET);
                                        output.accept(ModBlocks.TV);
                                        output.accept(ModBlocks.FLOOR_STANDING_SPEAKER);
                                        output.accept(ModBlocks.MODERN_CLOCK);
                                        output.accept(ModBlocks.MODERN_LIGHT);
                                        output.accept(ModBlocks.LED_FLOOR_LAMP);
                                        output.accept(ModBlocks.LED_FLOOR_LAMP_RGB_OFF);
                                        output.accept(ModBlocks.LED_RGB_TRIANGLE_PANEL);
                                        output.accept(ModBlocks.STUDIO_LIGHT);
                                        output.accept(ModBlocks.BLACK_GAMING_CHAIR);
                                        output.accept(ModBlocks.WHITE_GAMING_CHAIR);
                                        output.accept(ModBlocks.MONITOR_SETUP);
                                        output.accept(ModBlocks.MONITOR);
                                        output.accept(ModBlocks.BLACK_KEYBOARD);
                                        output.accept(ModBlocks.BLACK_COMPUTER_MOUSE);
                                        output.accept(ModBlocks.PC);
                                        output.accept(ModBlocks.PC_TOWER_GLASS);
                                        output.accept(ModBlocks.LAPTOP);
                                        output.accept(ModBlocks.PORTABLE_LAPTOP_STAND);
                                        output.accept(ModBlocks.LAPTOP_CLOSED_PORTABLE_LAPTOP_STAND);
                                        output.accept(ModBlocks.MIDI_KEYBOARD_CONTROLLER);
                                        output.accept(ModBlocks.MIDI_STANDALONE_GROOVEBOX);
                                        output.accept(ModBlocks.MIDI_STANDALONE_GROOVEBOX_2);
                                        output.accept(ModBlocks.MIDI_STANDALONE_GROOVEBOX_3);
                                        output.accept(ModBlocks.COOKTOP);
                                        output.accept(ModBlocks.FRIDGE_A);
                                        output.accept(ModBlocks.FRIDGE_B);
                                        output.accept(ModBlocks.MODERN_BATHROOM_SINK_STORAGE);
                                        output.accept(ModBlocks.MODERN_BATHROOM_MIRROR_SHELF);
                                        output.accept(ModBlocks.SHOWER);
                                        output.accept(ModBlocks.TOILET);
                                        output.accept(ModBlocks.WASHING_MACHINE_AI);
                                        output.accept(ModBlocks.PLANT_POT);
                                        output.accept(ModBlocks.BOOKS);
                                        output.accept(ModItems.WOOD_LIGHT_SQUARE_STICK);
                                        output.accept(ModItems.WOOD_MEDIUM_SQUARE_STICK);
                                        output.accept(ModItems.BLACK_SQUARE_STICK);
                                        output.accept(ModItems.WHITE_SQUARE_STICK);
                                        output.accept(ModItems.WOOD_LIGHT_SHORT_SQUARE_STICK);
                                        output.accept(ModItems.WOOD_MEDIUM_SHORT_SQUARE_STICK);
                                        output.accept(ModItems.BLACK_SHORT_SQUARE_STICK);
                                        output.accept(ModItems.WHITE_SHORT_SQUARE_STICK);
                                        output.accept(ModItems.WOOD_LIGHT_PANEL);
                                        output.accept(ModItems.WOOD_MEDIUM_PANEL);
                                        output.accept(ModItems.BLACK_PANEL);
                                        output.accept(ModItems.WHITE_PANEL);
                                        output.accept(ModBlocks.WOOD_LIGHT_DRAWER_SINGLE);
                                        output.accept(ModBlocks.WOOD_MEDIUM_DRAWER_SINGLE);
                                        output.accept(ModBlocks.BLACK_DRAWER_SINGLE);
                                        output.accept(ModBlocks.WHITE_DRAWER_SINGLE);
                                        output.accept(ModBlocks.BLACK_DESK_COLUMN);
                                        output.accept(ModBlocks.WHITE_DESK_COLUMN);
                                        output.accept(ModBlocks.WOOD_LIGHT_COMPARTMENT_STORAGE_CABINET);
                                        output.accept(ModBlocks.WOOD_MEDIUM_COMPARTMENT_STORAGE_CABINET);
                                        output.accept(ModBlocks.BLACK_COMPARTMENT_STORAGE_CABINET);
                                        output.accept(ModBlocks.WHITE_COMPARTMENT_STORAGE_CABINET);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_COMPARTMENT_STORAGE_CABINET);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_COMPARTMENT_STORAGE_CABINET);
                                        output.accept(ModBlocks.WOOD_LIGHT_KITCHEN_COMPARTMENT_STORAGE_CABINET_B);
                                        output.accept(ModBlocks.WOOD_MEDIUM_KITCHEN_COMPARTMENT_STORAGE_CABINET_B);
                                        output.accept(ModItems.REMOTE_CONTROL_RGB);
                                        output.accept(ModBlocks.COMPUTER_CASE);
                                        output.accept(ModItems.CPU);
                                        output.accept(ModItems.MAINBOARD);
                                        output.accept(ModItems.RAM);
                                        output.accept(ModItems.AIO_COOLER);
                                        output.accept(ModItems.COMPUTER_FAN);
                                        output.accept(ModItems.GPU);
                                        output.accept(ModItems.PSU);
                                    }).build());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> JS_FURNITURE_GARBAGE_ITEMS_GROUP = CREATIVE_MODE_TAB.register("js_furniture_trash",
            () -> CreativeModeTab.builder().title(Component.translatable("itemgroup.js_furniture_mod.js_trash_furniture_tab"))
                    .icon(() -> new ItemStack(ModItems.GARBAGE_ITEM.get()))
                    .displayItems((parameters, output) -> {
                        output.accept(ModBlocks.WOOD_CHAIR);
                        output.accept(ModBlocks.WOOD_COFFEE_TABLE);
                        output.accept(ModBlocks.WOOD_DESK);
                        output.accept(ModBlocks.WOOD_STANDING_DESK);
                        output.accept(ModBlocks.WOOD_STANDING_DESK_B);
                        output.accept(ModBlocks.WOOD_3_DRAWER_DRESSER);
                        output.accept(ModBlocks.KITCHEN_CABINET_BOTTOM);
                        output.accept(ModBlocks.KITCHEN_CABINET_BOTTOM_WITH_SINK);
                        output.accept(ModBlocks.KITCHEN_CABINET_BOTTOM_2);
                        output.accept(ModBlocks.KITCHEN_CABINET_BOTTOM_2_EXTRA);
                        output.accept(ModBlocks.KITCHEN_CABINET_BOTTOM_B);
                        output.accept(ModBlocks.KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
                        output.accept(ModBlocks.KITCHEN_CABINET_BOTTOM_B_2);
                        output.accept(ModBlocks.KITCHEN_DRAWERS);
                        output.accept(ModBlocks.KITCHEN_DRAWERS_B);
                        output.accept(ModBlocks.KITCHEN_CABINET_TOP);
                        output.accept(ModBlocks.KITCHEN_CABINET_TOP_B);
                        output.accept(ModBlocks.CEILING_FAN);
                        output.accept(ModBlocks.CEILING_FAN_B);
                        output.accept(ModBlocks.WOOD_STRIPED_WALL);
                        output.accept(ModBlocks.WOOD_MEDIUM_STRIPED_WALL);
                        output.accept(ModBlocks.SOFA);
                        output.accept(ModBlocks.MODERN_CHAIR);
                        output.accept(ModBlocks.VERTICAL_BLINDS);
                        output.accept(ModBlocks.KEYBOARD);
                        output.accept(ModBlocks.COMPUTER_MOUSE);
                    }).build());

    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TAB.register(eventBus);
    }
}
