package net.nhatjs.js_furniture_mod.datagen;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.nhatjs.js_furniture_mod.NhatJSFurnitureMod;
import net.nhatjs.js_furniture_mod.block.ModBlocks;
import net.nhatjs.js_furniture_mod.item.ModItems;

public class ModItemModelProvider extends ItemModelProvider {
    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, NhatJSFurnitureMod.MOD_ID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        basicItem(ModItems.REMOTE_CONTROL_RGB.get());
        basicItem(ModItems.CPU.get());
        basicItem(ModBlocks.BLACK_MIRROR.toStack().getItem());
        basicItem(ModItems.MAINBOARD.get());
        basicItem(ModItems.RAM.get());
        basicItem(ModItems.AIO_COOLER.get());
        basicItem(ModItems.COMPUTER_FAN.get());
        basicItem(ModItems.GPU.get());
        basicItem(ModItems.PSU.get());

        withExistingParent(ModBlocks.BLACK_GAMING_CHAIR.getId().toString(), modLoc("block/black_gaming_chair"));
        withExistingParent(ModBlocks.BLACK_SOFA.getId().toString(), modLoc("block/black_sofa"));
        withExistingParent(ModBlocks.BLACK_STANDING_DESK.getId().toString(), modLoc("block/black_standing_desk"));
        withExistingParent(ModBlocks.BLACK_STANDING_DESK_B.getId().toString(), modLoc("block/black_standing_desk_b"));
        withExistingParent(ModBlocks.BLACK_TABLE.getId().toString(), modLoc("block/black_table"));
        withExistingParent(ModBlocks.BOOKS.getId().toString(), modLoc("block/books"));
        withExistingParent(ModBlocks.CEILING_FAN.getId().toString(), modLoc("block/ceiling_fan"));
        withExistingParent(ModBlocks.CEILING_FAN_B.getId().toString(), modLoc("block/ceiling_fan_b"));
        withExistingParent(ModBlocks.COMPUTER_CASE.getId().toString(), modLoc("block/computer_case"));
        withExistingParent(ModBlocks.COMPUTER_MOUSE.getId().toString(), modLoc("block/computer_mouse"));
        withExistingParent(ModBlocks.COOKTOP.getId().toString(), modLoc("block/cooktop"));
        withExistingParent(ModBlocks.FLOOR_STANDING_SPEAKER.getId().toString(), modLoc("block/floor_standing_speaker"));
        withExistingParent(ModBlocks.FRIDGE_A.getId().toString(), modLoc("block/fridge_a"));
        withExistingParent(ModBlocks.FRIDGE_B.getId().toString(), modLoc("block/fridge_b"));
        withExistingParent(ModBlocks.KEYBOARD.getId().toString(), modLoc("block/keyboard"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_BOTTOM.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_bottom"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_BOTTOM_2.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_bottom_2"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_BOTTOM_2_EXTRA.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_bottom_2_extra"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_BOTTOM_B.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_bottom_b"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_BOTTOM_B_2.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_bottom_b_2"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_BOTTOM_B_WITH_SINK.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_bottom_b_with_sink"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_BOTTOM_WITH_SINK.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_bottom_with_sink"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_TOP.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_top"));
        withExistingParent(ModBlocks.KITCHEN_CABINET_TOP_B.getId().toString(), modLoc("block/light_wood_kitchen_cabinet_top_b"));
        withExistingParent(ModBlocks.KITCHEN_DRAWERS.getId().toString(), modLoc("block/light_wood_kitchen_drawers"));
        withExistingParent(ModBlocks.KITCHEN_DRAWERS_B.getId().toString(), modLoc("block/light_wood_kitchen_drawers_b"));
        withExistingParent(ModBlocks.LAPTOP.getId().toString(), modLoc("block/laptop_opened_off"));
        withExistingParent(ModBlocks.LAPTOP_CLOSED_PORTABLE_LAPTOP_STAND.getId().toString(), modLoc("block/laptop_closed_portable_laptop_stand"));
        withExistingParent(ModBlocks.LED_FLOOR_LAMP.getId().toString(), modLoc("block/led_floor_lamp_off"));
        withExistingParent(ModBlocks.LED_FLOOR_LAMP_RGB_OFF.getId().toString(), modLoc("block/led_floor_lamp_rgb_off"));
        withExistingParent(ModBlocks.LED_FLOOR_LAMP_RGB_OFF_2.getId().toString(), modLoc("block/led_floor_lamp_rgb_off_2"));
        withExistingParent(ModBlocks.LED_RGB_TRIANGLE_PANEL.getId().toString(), modLoc("block/led_rgb_triangle_panel"));
        withExistingParent(ModBlocks.MIDI_KEYBOARD_CONTROLLER.getId().toString(), modLoc("block/midi_keyboard_controller"));
        withExistingParent(ModBlocks.MIDI_STANDALONE_GROOVEBOX.getId().toString(), modLoc("block/midi_standalone_groovebox"));
        withExistingParent(ModBlocks.MIDI_STANDALONE_GROOVEBOX_2.getId().toString(), modLoc("block/midi_standalone_groovebox_2"));
        withExistingParent(ModBlocks.MIDI_STANDALONE_GROOVEBOX_3.getId().toString(), modLoc("block/midi_standalone_groovebox_3"));
        withExistingParent(ModBlocks.MODERN_BATHROOM_MIRROR_SHELF.getId().toString(), modLoc("block/modern_bathroom_mirror_shelf"));
        withExistingParent(ModBlocks.MODERN_BATHROOM_SINK_STORAGE.getId().toString(), modLoc("block/modern_bathroom_sink_storage"));
        withExistingParent(ModBlocks.MODERN_CHAIR.getId().toString(), modLoc("block/modern_chair"));
        withExistingParent(ModBlocks.MODERN_CLOCK.getId().toString(), modLoc("block/modern_clock"));
        withExistingParent(ModBlocks.MODERN_LIGHT.getId().toString(), modLoc("block/modern_light_off"));
        withExistingParent(ModBlocks.MONITOR.getId().toString(), modLoc("block/monitor"));
        withExistingParent(ModBlocks.MONITOR_SETUP.getId().toString(), modLoc("block/monitor_setup"));
        withExistingParent(ModBlocks.PC.getId().toString(), modLoc("block/pc"));
        withExistingParent(ModBlocks.PC_ADDED_1.getId().toString(), modLoc("block/pc_added_1"));
        withExistingParent(ModBlocks.PC_ADDED_2.getId().toString(), modLoc("block/pc_added_2"));
        withExistingParent(ModBlocks.PC_ADDED_3.getId().toString(), modLoc("block/pc_added_3"));
        withExistingParent(ModBlocks.PC_ADDED_4.getId().toString(), modLoc("block/pc_added_4"));
        withExistingParent(ModBlocks.PC_ADDED_5.getId().toString(), modLoc("block/pc_added_5"));
        withExistingParent(ModBlocks.PC_ADDED_6.getId().toString(), modLoc("block/pc_added_6"));
        withExistingParent(ModBlocks.PC_ADDED_7.getId().toString(), modLoc("block/pc_added_7"));
        withExistingParent(ModBlocks.PC_ADDED_8.getId().toString(), modLoc("block/pc_added_8"));
        withExistingParent(ModBlocks.PC_ADDED_9.getId().toString(), modLoc("block/pc_added_9"));
        withExistingParent(ModBlocks.PC_ADDED_10.getId().toString(), modLoc("block/pc_added_10"));
        withExistingParent(ModBlocks.PC_ADDED_11.getId().toString(), modLoc("block/pc_added_11"));
        withExistingParent(ModBlocks.PC_TOWER_GLASS.getId().toString(), modLoc("block/pc_tower_glass"));
        withExistingParent(ModBlocks.PLANT_POT.getId().toString(), modLoc("block/plant_pot"));
        withExistingParent(ModBlocks.PORTABLE_LAPTOP_STAND.getId().toString(), modLoc("block/portable_laptop_stand"));
        withExistingParent(ModBlocks.SHOWER.getId().toString(), modLoc("block/shower"));
        withExistingParent(ModBlocks.SOCKET.getId().toString(), modLoc("block/socket"));
        withExistingParent(ModBlocks.SOFA.getId().toString(), modLoc("block/white_sofa"));
        withExistingParent(ModBlocks.STUDIO_LIGHT.getId().toString(), modLoc("block/studio_light_off"));
        withExistingParent(ModBlocks.TOILET.getId().toString(), modLoc("block/toilet"));
        withExistingParent(ModBlocks.TV.getId().toString(), modLoc("block/tv"));
        withExistingParent(ModBlocks.VERTICAL_BLINDS.getId().toString(), modLoc("block/vertical_blinds"));
        withExistingParent(ModBlocks.WASHING_MACHINE_AI.getId().toString(), modLoc("block/washing_machine_ai_off"));
        withExistingParent(ModBlocks.WHITE_3_DRAWER_DRESSER.getId().toString(), modLoc("block/white_3_drawer_dresser"));
        withExistingParent(ModBlocks.WHITE_CHAIR.getId().toString(), modLoc("block/white_chair"));
        withExistingParent(ModBlocks.WHITE_COFFEE_TABLE.getId().toString(), modLoc("block/white_coffee_table"));
        withExistingParent(ModBlocks.WHITE_DESK.getId().toString(), modLoc("block/white_desk"));
        withExistingParent(ModBlocks.WHITE_GAMING_CHAIR.getId().toString(), modLoc("block/white_gaming_chair"));
        withExistingParent(ModBlocks.WHITE_STANDING_DESK.getId().toString(), modLoc("block/white_standing_desk"));
        withExistingParent(ModBlocks.WHITE_STANDING_DESK_B.getId().toString(), modLoc("block/white_standing_desk_b"));
        withExistingParent(ModBlocks.WHITE_TABLE.getId().toString(), modLoc("block/white_table"));
        withExistingParent(ModBlocks.WHITE_TV_STAND.getId().toString(), modLoc("block/tv_stand_2"));
        withExistingParent(ModBlocks.WOOD_3_DRAWER_DRESSER.getId().toString(), modLoc("block/light_wood_3_drawer_dresser"));
        withExistingParent(ModBlocks.WOOD_CHAIR.getId().toString(), modLoc("block/light_wood_chair"));
        withExistingParent(ModBlocks.WOOD_COFFEE_TABLE.getId().toString(), modLoc("block/light_wood_coffee_table"));
        withExistingParent(ModBlocks.WOOD_DESK.getId().toString(), modLoc("block/light_wood_desk"));
        withExistingParent(ModBlocks.WOOD_LIGHT_TABLE.getId().toString(), modLoc("block/light_wood_table"));
        withExistingParent(ModBlocks.WOOD_LIGHT_TV_STAND.getId().toString(), modLoc("block/light_wood_tv_stand"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_3_DRAWER_DRESSER.getId().toString(), modLoc("block/medium_wood_3_drawer_dresser"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_CHAIR.getId().toString(), modLoc("block/medium_wood_chair"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_COFFEE_TABLE.getId().toString(), modLoc("block/medium_wood_coffee_table"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_DESK.getId().toString(), modLoc("block/medium_wood_desk"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_bottom"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_2.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_bottom_2"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_2_EXTRA.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_bottom_2_extra"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_bottom_b"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B_2.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_bottom_b_2"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B_WITH_SINK.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_bottom_b_with_sink"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_WITH_SINK.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_bottom_with_sink"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_TOP.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_top"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_TOP_B.getId().toString(), modLoc("block/medium_wood_kitchen_cabinet_top_b"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_DRAWERS.getId().toString(), modLoc("block/medium_wood_kitchen_drawers"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_KITCHEN_DRAWERS_B.getId().toString(), modLoc("block/medium_wood_kitchen_drawers_b"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_STANDING_DESK.getId().toString(), modLoc("block/medium_wood_standing_desk"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_STANDING_DESK_B.getId().toString(), modLoc("block/medium_wood_standing_desk_b"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_STRIPED_WALL.getId().toString(), modLoc("block/medium_wood_striped_wall"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_TABLE.getId().toString(), modLoc("block/medium_wood_table"));
        withExistingParent(ModBlocks.WOOD_MEDIUM_TV_STAND.getId().toString(), modLoc("block/medium_wood_tv_stand"));
        withExistingParent(ModBlocks.WOOD_STANDING_DESK.getId().toString(), modLoc("block/light_wood_standing_desk"));
        withExistingParent(ModBlocks.WOOD_STANDING_DESK_B.getId().toString(), modLoc("block/light_wood_standing_desk_b"));
        withExistingParent(ModBlocks.WOOD_STRIPED_WALL.getId().toString(), modLoc("block/light_wood_striped_wall"));
    }
}
